package com.prestamos.dto;
// Generated 17/07/2014 03:01:05 PM by Hibernate Tools 3.6.0



/**
 * UsuarioId generated by hbm2java
 */
public class UsuarioId  implements java.io.Serializable {


    /**
     * Tipo de documento de identificación del usuario
     */
     private String tipoDocumento;
     /**
      * Número de documento de identificación del usuario
      */
     private String numeroDocumento;

     //Constructores
    public UsuarioId() {
    }

    public UsuarioId(String tipoDocumento, String numeroDocumento) {
       this.tipoDocumento = tipoDocumento;
       this.numeroDocumento = numeroDocumento;
    }
   
    //Setters and getters
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }

/**
 * Metodo que compara 2 usuarioid
 * @param other es el usuarioid con el que se va a comparar
 * @return un booleano
 */
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioId) ) return false;
		 UsuarioId castOther = ( UsuarioId ) other; 
         
		 return ( (this.getTipoDocumento()==castOther.getTipoDocumento()) || ( this.getTipoDocumento()!=null && castOther.getTipoDocumento()!=null && this.getTipoDocumento().equals(castOther.getTipoDocumento()) ) )
 && ( (this.getNumeroDocumento()==castOther.getNumeroDocumento()) || ( this.getNumeroDocumento()!=null && castOther.getNumeroDocumento()!=null && this.getNumeroDocumento().equals(castOther.getNumeroDocumento()) ) );
   }
   
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTipoDocumento() == null ? 0 : this.getTipoDocumento().hashCode() );
         result = 37 * result + ( getNumeroDocumento() == null ? 0 : this.getNumeroDocumento().hashCode() );
         return result;
   }   


}


