package com.prestamos.dto;
// Generated 17/07/2014 03:01:05 PM by Hibernate Tools 3.6.0



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


    /**
     * Identificador del usuario
     */
     private UsuarioId id;
     /**
      * Tipo de usuario
      */
     private TipoUsuario tipoUsuario;
     /**
      * Nombres del usuario
      */
     private String nombres;
     /**
      * Apellidos del usuario
      */
     private String apellidos;
     /**
      * Dirección de correo electrónico del usuario
      */
     private String correo;
     /**
      * Estado del usuario en el sistema
      */
     private String estado;

     //Constructores
    public Usuario() {
    }

    public Usuario(UsuarioId id, TipoUsuario tipoUsuario, String nombres, String apellidos, String correo, String estado) {
       this.id = id;
       this.tipoUsuario = tipoUsuario;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.correo = correo;
       this.estado = estado;
    }
   
    //Setters and getters
    public UsuarioId getId() {
        return this.id;
    }
    
    public void setId(UsuarioId id) {
        this.id = id;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


